version: '3'

services:
    protonvpn-docker-jp:
        image: protonvpn-docker
        stdin_open: true
        tty: true
        environment:
            - SOCKD_WORKERS=10
            - ProtonServer=JP
        ports:
            - "1080:1080"
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"
        command: java -Dserver.port=8081  -jar /root/SendSkinPrices.jar
        volumes:
            - "./startup.sh:/root/startup.sh"
            - "./SendSkinPrices.jar:/root/SendSkinPrices.jar"

    protonvpn-docker-nl1:
        image: protonvpn-docker
        stdin_open: true
        tty: true
        environment:
            - SOCKD_WORKERS=10
            - ProtonServer=NL
        ports:
            - "1081:1080"
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"
        command: java -Dserver.port=8082  -jar /root/SendSkinPrices.jar
        volumes:
            - "./startup.sh:/root/startup.sh"
            - "./SendSkinPrices.jar:/root/SendSkinPrices.jar"

    protonvpn-docker-us:
        image: protonvpn-docker
        stdin_open: true
        tty: true
        environment:
            - SOCKD_WORKERS=10
            - ProtonServer=US
        ports:
            - "1082:1080"
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"
        command: java -Dserver.port=8083 -jar /root/SendSkinPrices.jar
        volumes:
            - "./startup.sh:/root/startup.sh"
            - "./SendSkinPrices.jar:/root/SendSkinPrices.jar"  
